### ISSUE TITLE
Clarify situation with respect to in-person ballots

### ISSUE THREAD

**Issue by cjerdonek** [votingworks/vxmail#10]
This issue is for the docs to clarify how and whether VxMail will support ballots generated from a different system, or if this is limited only to all-mail elections.

Since many jurisdictions will likely be tied to existing processes and vendors for their in-person ballots (extending from election definition to ballot design, layout, and printing, etc), how does VxMail plan to operate in conjunction with those systems? For example, are there circumstances in which VxMail would be able to use the ballots produced from those existing processes as is? If not, is that on the future roadmap (e.g. will it have an architecture that's at least forward compatible with scanning ballots coming from a third party)? Otherwise, jurisdictions will need to duplicate all of those ballot-generation processes.

Related to this, assuming VxMail isn't limited to jurisdictions doing all-mail elections, I think there is a step that needs to be documented about combining VxMail's vote totals with the vote totals from the jurisdiction's existing system for in-person ballots, either by importing totals from the other system into VxMail, or vice versa. Note that I'm not sure it's a given that existing systems necessarily allow mass importing totals from an outside system, so it might be easier to do the former. However, if you do the former, you'll also need a solution for reporting election results, since it won't be doable with the usual system (since VxMail's votes can't be incorporated).

This is an issue that [OSVTAC](https://github.com/OSVTAC) which I chair has discussed, which is why we recommended an approach that would permit centrally scanning ballots generated by a third-party. It allows for a rollout that takes advantage of those existing systems. See here, for example: https://osvtac.github.io/recommendations/implementation-order#7-recommended-implementation-order

**Comment by benadida** [comment]
Great comment, thank you.

Our planned approach right now is to enable the combination of results from multiple systems, rather than scan ballots printed by other systems (which is a good bit harder to test.) We'll be adding to the spec to describe this.
