### ISSUE TITLE
Need to check envelope contains correct ballot

### ISSUE THREAD

**Issue by cjerdonek** [votingworks/vxmail#12]
In the "Opening Envelopes and Extracting Ballots" section, it seems like you need a step to check that the ballot type of the ballot inside an envelope matches the voter's ballot type. In the obvious approach, you need to do this when extracting the ballot as opposed to during the scanning stage, because in the scanning stage you no longer have the ballot-to-voter association. If the ballot type doesn't match, I'm not sure how this is recorded in the EMS (e.g. did the voter vote, even if the voter wasn't eligible to vote in any of the contests they submitted?).

Alternatively, if you don't make a distinction in the EMS record, a way to do this check during the scanning stage would be to make an imprint on the ballot during the extraction stage of what the _expected_ ballot type is. And then when scanning, you can compare the actual type to the expected type and act accordingly.

**Comment by cjerdonek** [comment]
This also brings to mind the following edge case: if the wrong ballot type is in an envelope, but it overlaps with the correct ballot type, do you count the votes in the overlap? Since it probably wouldn't be worth making the scanner sophisticated enough to handle this case, you would likely need a process here (e.g. remaking the ballot onto the correct ballot type so the new ballot could be used in the scanner).

This "overlap" scenario is more common with provisional voters (e.g. in San Francisco). If a voter goes to the wrong polling place, they vote a provisional ballot at that precinct. When the provisional envelope is opened, if the ballot type doesn't match, the voter's votes are still counted for those contests that overlap with the correct ballot type.

**Comment by benadida** [comment]
archiving this issue for now as we've put this work on pause for the moment.
