### ISSUE TITLE
election-manager: in proofing, just show the actual ballot

### ISSUE THREAD

**Issue by benadida** [votingworks/vxmail#146]
might as well, instead of the unrendered title etc.

**Comment by mcchilders** [comment]
@benadida can we do both? (Toggle between ballot PDF and human-readable? Or, MVP, PDF on top and text definition below that?) 

I actually think proofing things like name spelling, are all the candidates there, are they in the right order etc. is a lot easier to do in the text version, so wouldn't want to lose that entirely.
