### ISSUE TITLE
understand and possibly standardize all the ways write-ins are represented in CVRs for BMD and HMPB

### ISSUE THREAD

**Issue by benadida** [votingworks/vxmail#159]
including `__write-in-0` in HMPB which probably needs to be adjusted before CVR export.

**Comment by benadida** [comment]
I think this is solved, but worth checking.

**Comment by eventualbuddha** [comment]
https://docs.google.com/document/d/1ZsirbmIUGk6ir0SfImaDv1Pg6gIdVlKUkJAQhrleb5o/edit

This ^ covers where we produce and consume write-in IDs. Should we bother standardizing now? I think for m10 we don't need to.
