### ISSUE TITLE
make sure scanner produces CVRs with empty array for contests that are fully undervoted

### ISSUE THREAD

**Issue by benadida** [votingworks/vxmail#192]

**Comment by eventualbuddha** [comment]
Confirmed with these images:

![manual-batch-0001](https://user-images.githubusercontent.com/1938/92166804-19425b80-edee-11ea-8e72-e29f22d90dfb.png)
![manual-batch-0002](https://user-images.githubusercontent.com/1938/92166840-2bbc9500-edee-11ea-8f02-6ee08509ab34.png)

```json
{"775020858":[],"_ballotId":"8b586621-8493-4349-a5a0-e2c1777f5da2","_ballotStyleId":"1","_precinctId":"6526","_scannerId":"000","_testBallot":false,"_locales":{"primary":"en-US"},"_pageNumbers":[1,2]}
```

I edited the image to (mostly) remove a vote for the third candidate so I could perform this test.
