### ISSUE TITLE
scanner misbehaves on fresh start

### ISSUE THREAD

**Issue by benadida** [votingworks/vxmail#230]
Steps to repro:
- delete `ballots.db*` files in `module-scan`
- load election package
- switch to test mode (this appears to be relevant, issue does not come up in live mode with live ballots.)
- scan a few test ballots

You should see all ballots rejected.

If you now restart module-scan without removing the DB files, it then works.

Notes:
- factory reset does NOT simulate the same thing as deleting the `ballots.db*` files, will not repro the problem.
- zero'ing the scanner from broken state does NOT fix it.
- factory reset the scanner from broken state does NOT fix it either.
- only a restart of `module-scan` fixes it.
- the failure looks a lot like when scanning test ballots in live mode. I'm wondering if some aspect of the test mode setting is recorded in the DB but not in memory until the restart?

One more broken state:
- switching from test to live without a restart ALSO fails.
- switching back to test does NOT fix it.
- "it's the switching without restarting that's broken."

**Comment by eventualbuddha** [comment]
Any reproduction hints?
