### ISSUE TITLE
Add CVR export complete notification

### ISSUE THREAD

**Issue by mattroe** [votingworks/vxmail#280]
https://votingworks.slack.com/archives/C017ZU12GEM/p1601328900035800

**Comment by benadida** [comment]
This happens because of USB ejection and file syncing. We currently don't have a way to detect that, so closing this issue for now.

**Comment by benadida** [comment]
@mattroe The delay here is USB flush, not the actual saving of the file, and we don't have a handle on when that happens. Right now we just have to give guidance to clerks and say "Wait 10s after saving, and 15s after clicking eject to remove the USB stick."

We'll have to improve this later!
