### ISSUE TITLE
review storage in module-scan

### ISSUE THREAD

**Issue by benadida** [votingworks/vxmail#290]
because the SVG in the election.json is blowing up usage of sqlite.

**Comment by eventualbuddha** [comment]
This doesn't seem like a large value, right? Or is it just because we're copying the contest data all over the place?

**Comment by benadida** [comment]
because this gets repeated a lot, it adds up. I'm thinking the easiest solution is to pre-process the election data and pare down every field that isn't strictly necessary to `module-scan`, so that no code changes, but less data is used up.
