### ISSUE TITLE
Election Manager: overvote combination tabulation report in election manager

### ISSUE THREAD

**Issue by benadida** [votingworks/vxmail#31]
This is a special overvote report that is separate from the main report, though should be refinable by tabulator, ballot style, precinct, like the other report. It should present all pairwise combinations of candidates for which overvotes exist that include that pair, and show the count.

For example, if the CVRs with overvotes are:
- Alice, Bob, Charlie
- Alice, Bob
- Alice, Charlie
- Alice, David

Then the report should say:

- Alice & Bob – 2
- Bob & Charlie – 1
- Alice & Charlie – 2
- Alice & David – 1

and shouldn't list any other combinations.

**Comment by eventualbuddha** [comment]
Is this “all pairs of selected candidates for over-voted contests”? So if it’s A, B and C selected then you’d have three pairs (A, B), (B, C), and (A, C)?
