### ISSUE TITLE
"select election definition file" in starting screen of election manager doesn't work.

### ISSUE THREAD

**Issue by benadida** [votingworks/vxmail#51]
The button doesn't appear to do anything, and I can't figure out why.

**Comment by beausmith** [comment]
Stupid HTML. Yeah, I found and fixed this last week.

Make sure you're on latest master.

**Comment by beausmith** [comment]
Oh, my bad. This commit need to be cherry-picked: 

https://github.com/votingworks/election-manager/commit/470384252706057aaddae6f4b6b3625ece8483c9

It's on the shelved "definition editor" branch.

**Comment by beausmith** [comment]
https://github.com/votingworks/election-manager/pull/32
