### ISSUE TITLE
Election Manager: have a mode that switches reports to "official"

### ISSUE THREAD

**Issue by benadida** [votingworks/vxmail#76]
The user should be able to flip a bit that indicates "all the CVRs are in, reports from now on are OFFICIAL" and the reports should print that accordingly. Otherwise print "Unofficial".

Note: as part of the same process, reports should print the *date and time* at which they are generated.

**Comment by beausmith** [comment]
Card is covered by: https://zube.io/votingworks/vxmail/c/85
